### ISSUE TITLE
Ch4 urls also wrong in text and sample app

### ISSUE THREAD

**Issue by flowt-au** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#25]
As per Ch2: [https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/20](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/20)

**Comment by stianst** [comment]
This issue is caused by breaking changes in recent versions of Keycloak, for more details and how to workaround the issues take a look [here](https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26).

I'm closing this issue for now as a duplicate of https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/issues/26.
